name: chatty
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.2.12
  flutter_easyloading: ^3.0.5
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  crypto: ^3.0.6
  webview_flutter: ^4.10.0
  loading_animations: ^2.2.0
  share: ^2.0.4
  device_info: ^2.0.3
  package_info: ^2.0.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  sentry: ^8.13.2
  uni_links: ^0.5.1
  flutter_spinkit: ^5.2.1
  dots_indicator: ^4.0.1
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_in_app_messaging: ^0.8.1+4
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  location: ^7.0.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  sqflite: ^2.4.1
  flutter_verification_code: ^1.1.7
  agora_rtc_engine: ^6.5.0
  just_audio: ^0.9.46
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - assets/dang.mp3
    - assets/ding.mp3
    - assets/gif.gif
    - assets/jpg.jpg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
